"""empty message

Revision ID: 042405b6622a
Revises: be2c032b498f
Create Date: 2022-02-04 23:55:18.290403

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '042405b6622a'
down_revision = 'be2c032b498f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alunos_materias',
    sa.Column('aluno_id', sa.Integer(), nullable=True),
    sa.Column('materia_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['aluno_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['materia_id'], ['materias.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('alunos_materias')
    # ### end Alembic commands ###
