"""empty message

Revision ID: 1f3d7b834f7c
Revises: eeb6c3403f7d
Create Date: 2022-02-05 07:54:15.819501

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1f3d7b834f7c'
down_revision = 'eeb6c3403f7d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('alunos_presenca_aulas', 'id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('alunos_presenca_aulas', 'aluno_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('alunos_presenca_aulas', 'aula_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('alunos_presenca_aulas', 'aula_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('alunos_presenca_aulas', 'aluno_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('alunos_presenca_aulas', 'id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
