"""empty message

Revision ID: eeb6c3403f7d
Revises: 042405b6622a
Create Date: 2022-02-05 01:42:13.993879

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eeb6c3403f7d'
down_revision = '042405b6622a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alunos_presenca_aulas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('aluno_id', sa.Integer(), nullable=True),
    sa.Column('aula_id', sa.Integer(), nullable=True),
    sa.Column('presente', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['aluno_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['aula_id'], ['aulas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('alunos_aulas')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alunos_aulas',
    sa.Column('aluno_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('aula_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['aluno_id'], ['usuarios.id'], name='alunos_aulas_aluno_id_fkey'),
    sa.ForeignKeyConstraint(['aula_id'], ['aulas.id'], name='alunos_aulas_aula_id_fkey')
    )
    op.drop_table('alunos_presenca_aulas')
    # ### end Alembic commands ###
